// Original sample film data — fictional + public-domain titles, no real branding.
// Posters are CSS-generated placeholder cards (no copyrighted artwork).

const FILMS = [
  { id: 'f01', title: 'The Long Quiet', year: 2023, runtime: 118, director: 'Ines Marchetti',
    genres: ['Drama', 'Mystery'], rating: 4.5, watched: false,
    palette: ['#1a1f2e', '#c9a961'], shape: 'mono',
    tagline: 'A village. A river. A summer that refuses to end.',
    synopsis: 'When a long-dead photographer\u2019s archive resurfaces in a Ligurian town, a young archivist is forced to reconcile two versions of her grandmother.' },
  { id: 'f02', title: 'Northing', year: 2024, runtime: 96, director: 'Sam Okafor',
    genres: ['Sci-Fi', 'Thriller'], rating: 0, watched: false,
    palette: ['#0d2b2b', '#7adfd0'], shape: 'split',
    tagline: 'Up is a direction. Home is not.',
    synopsis: 'A surveyor mapping a contested arctic shelf begins receiving radio transmissions from a station that was never built.' },
  { id: 'f03', title: 'Mirror, Mirror', year: 2022, runtime: 104, director: 'Lila Vance',
    genres: ['Horror', 'Drama'], rating: 4, watched: true,
    palette: ['#2a0e1a', '#e84a5f'], shape: 'circle',
    tagline: 'You can\u2019t hide from a room that remembers.',
    synopsis: 'Twin sisters inherit a hotel built around a single, unshatterable mirror.' },
  { id: 'f04', title: 'Cassette Future', year: 2021, runtime: 89, director: 'Hideo Tanaka',
    genres: ['Comedy', 'Romance'], rating: 3.5, watched: true,
    palette: ['#1a1530', '#ff6ec7'], shape: 'stripe',
    tagline: 'Rewind. Repeat. Rewrite.',
    synopsis: 'A repair-shop clerk in 1986 Osaka discovers a cassette that plays tomorrow\u2019s news.' },
  { id: 'f05', title: 'Saltlight', year: 2024, runtime: 132, director: 'Ana Beltr\u00e1n',
    genres: ['Drama'], rating: 0, watched: false,
    palette: ['#f4ede0', '#7a8b6f'], shape: 'mono',
    tagline: 'Three sisters. One coastline. Forty years.',
    synopsis: 'An epic that follows three sisters across decades on the Galician coast.' },
  { id: 'f06', title: 'Concrete Garden', year: 2023, runtime: 111, director: 'Yusuf Ahmadi',
    genres: ['Drama', 'Documentary'], rating: 5, watched: true,
    palette: ['#2d2a26', '#d4a574'], shape: 'block',
    tagline: 'They built a city on a promise.',
    synopsis: 'Five families share a single Brutalist apartment block over the course of one impossible summer.' },
  { id: 'f07', title: 'Hummingbird Method', year: 2022, runtime: 98, director: 'Priya Raman',
    genres: ['Thriller'], rating: 0, watched: false,
    palette: ['#0a1a0f', '#5fcf6e'], shape: 'split',
    tagline: 'Move fast. Leave nothing.',
    synopsis: 'A retired cat burglar takes one last commission \u2014 from herself, twenty years younger.' },
  { id: 'f08', title: 'Paper Moons', year: 2025, runtime: 124, director: 'Eva Rohrer',
    genres: ['Animation', 'Family'], rating: 0, watched: false,
    palette: ['#fff4d6', '#e8804f'], shape: 'circle',
    tagline: 'Look up. Wish bigger.',
    synopsis: 'A papercraft animated fable about a girl who runs the night sky from her bedroom.' },
  { id: 'f09', title: 'Static Bloom', year: 2020, runtime: 87, director: 'Marko Pavi\u0107',
    genres: ['Sci-Fi'], rating: 4, watched: true,
    palette: ['#1f1a2e', '#a98ce8'], shape: 'stripe',
    tagline: 'The signal was always you.',
    synopsis: 'A radio operator in a near-future Belgrade falls in love with a voice that may not exist.' },
  { id: 'f10', title: 'Fieldnotes', year: 2024, runtime: 142, director: 'Theodora Klein',
    genres: ['Documentary'], rating: 0, watched: false,
    palette: ['#e8e0d0', '#3a4a2a'], shape: 'mono',
    tagline: 'Forty years on a single hill.',
    synopsis: 'An entomologist returns to the same meadow every summer for forty years.' },
  { id: 'f11', title: 'Lowtide', year: 2023, runtime: 93, director: 'James Korrigan',
    genres: ['Drama', 'Romance'], rating: 4.5, watched: true,
    palette: ['#0e2233', '#ffb877'], shape: 'block',
    tagline: 'Some letters take a lifetime to send.',
    synopsis: 'Two old friends meet on a Cornish beach to deliver a letter neither of them wants to read.' },
  { id: 'f12', title: 'Vesper, Returning', year: 2025, runtime: 108, director: 'Nadia Khoury',
    genres: ['Drama', 'Mystery'], rating: 0, watched: false,
    palette: ['#1d1a30', '#c5b4e0'], shape: 'circle',
    tagline: 'She came home. Home didn\u2019t.',
    synopsis: 'A war correspondent returns to the Lebanon of her childhood and finds her old apartment occupied by a stranger who knows her name.' },
  { id: 'f13', title: 'The Bureau of Small Hours', year: 2022, runtime: 119, director: 'August Lindqvist',
    genres: ['Comedy', 'Drama'], rating: 4, watched: true,
    palette: ['#2a2218', '#f1d3a3'], shape: 'split',
    tagline: 'Closed nights. Closed weekends. Closed forever.',
    synopsis: 'The world\u2019s most boring civil servant accidentally outlives his department by forty years.' },
  { id: 'f14', title: 'Blue Hour Witness', year: 2024, runtime: 101, director: 'Reza Farahani',
    genres: ['Thriller', 'Drama'], rating: 0, watched: false,
    palette: ['#0a1a3a', '#6ba3ff'], shape: 'mono',
    tagline: 'You only saw a moment. The moment saw everything.',
    synopsis: 'An urban photographer realizes she captured the exact instant of a disappearance \u2014 and is the only person who can prove it didn\u2019t happen the way the police say.' },
  { id: 'f15', title: 'Folktale for the Modem Age', year: 2021, runtime: 85, director: 'Rin Yamashita',
    genres: ['Animation', 'Sci-Fi'], rating: 5, watched: true,
    palette: ['#1a0a2e', '#ff5da2'], shape: 'stripe',
    tagline: 'Once upon a 56k.',
    synopsis: 'In a town built inside a dial-up modem, a kitsune learns to ping.' },
  { id: 'f16', title: 'A Field of Smaller Suns', year: 2025, runtime: 137, director: 'Awa Sangar\u00e9',
    genres: ['Drama'], rating: 0, watched: false,
    palette: ['#3a1f0f', '#ffc870'], shape: 'block',
    tagline: 'Light, divided.',
    synopsis: 'In a Senegalese coastal town, a solar engineer and a fisherman build something neither of them planned for.' },
];

window.FILMS = FILMS;
